---

repo: https://github.com/bratsche/pango

configurations:
  - 0:
      Feature Scaling: zScore
      Feature Selection: kbest
      Data Balancing: smote
      Classifier: randomforest
      Validation: ttsplit
      Explaination Method: confusionmatrix