---

repo: https://github.com/klauspost/compress

configurations:
  - 0:
      Feature Scaling: zScore
      Feature Selection: kbest
      Data Balancing: smote
      Hyper-parameters Optimization: RandomSearch
      Classifier: svm
      Validation: ttsplit
      Metric: accuracy
      Explaination Method: confusionmatrix
  - 1:
      Data Cleaning: dataimputation
      Feature Scaling: zScore
      Feature Selection: kbest
      Data Balancing: smote
      Hyper-parameters Optimization: RandomSearch
      Classifier: svm
      Validation: ttsplit
      Metric: precision
      Explaination Method: confusionmatrix