---


repo: https://github.com/ultrajson/ultrajson

configurations:
   - 0:
        Feature Scaling: zscore
        Data Balancing: smote
        Classifier: svm
        Validation: ttsplit
        Explanation Method: confusionmatrix

   - 1:
       Feature Scaling: zscore
       Data Balancing: smote
       Classifier: randomforest
       Validation: ttsplit
       Explanation Method: permutation

   - 2:
       Feature Scaling: zscore
       Data Balancing: smote
       Classifier: kneighbors
       Validation: ttsplit
       Explanation Method: partialdependence


statistical test:
      - 0: 0, 1
      - 1: 1, 2