---

repo: https://github.com/bratsche/pango
dataset: "dataset_pango.csv"

configurations:
  - 0:
      Feature Selection: kbest
      K: 4
      Feature Scaling: minmax
      Data Balancing: smote
      Classifier: randomforest
      Validation: ttsplit
      Explaination Method: confusionmatrix