---

repo: https://github.com/klauspost/compress

configurations:
  - 0:
      Feature Scaling: zScore
      Feature Selection: kbest
      Data Balancing: smote
      Classifier: svm
      Validation: ttsplit
      Explaination Method: confusionmatrix
  - 1:
      Data Cleaning: shuffling
      Feature Scaling: zScore
      Feature Selection: kbest
      Data Balancing: smote
      Classifier: svm
      Validation: ttsplit
      Explaination Method: confusionmatrix