---

repo: https://github.com/bratsche/pango

configurations:
    - 0:
          Feature Scaling: zscore
          Data Balancing: smote
          Classifier: randomforest
          Validation: ttsplit
          Explanation Method: permutation
    - 1:
          Feature Scaling: minmax
          Data Balancing: smote
          Classifier: randomforest
          Validation: ttsplit
          Explanation Method: permutation

statistical test:
      - 0: 1, 0